name: workflow_dispatch
on: push

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: "Say hello"
        run: echo "Hello, World"
  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: "Succesfull step"
        run: |
          echo "I"
          echo "Will"
          echo "Succes"
          exit 0
      - name: "Say goodbye"
        run: echo "Goodbye!"
