name: 05 - 1 - Events Filters and Activitu Types
on:
    pull_request:
        types: [opened, synchronize]
        branches:
            - main
            
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: echo-pr
              run: echo "Running whenever a PR is opened or synchronized AND base branch is main"
