name: 06 - Contexts
run-name: y custom workflow run name - ${{ runnner.os }}
on:
    workflow_dispatch:
    push:
jobs:
    echo-data:
        runs-on: ubuntu-latest
        steps:
            - name: Display-information
              run: |
                    echo "Event name: $GITHUB_EVENT_NAME"
                    echo "GITHUB_SHA: $GITHUB_SHA"
                    echo "GITHUB_REF: $GITHUB_REF"
                    echo "GITHUB_ACTOR: $GITHUB_ACTOR"
                    echo "GITHUB_JOB: $GITHUB_JOB"
                    echo "GITHUB_WORKFLOW: $GITHUB_WORKFLOW"
                    echo "GITHUB_RUN_ID: $GITHUB_RUN_ID"
                    echo "GITHUB_RUN_NUMBER: $GITHUB_RUN_NUMBER"
            - name: Retrieve Variable
              run: echo "The value of the variable is ${{ vars.MY_VAR }}"
            