name: 06 - Contexts
run-name: 06 - Contexts | DEBUG - ${{ inputs.debug }}
on:
    workflow_dispatch:
        inputs:
            debug:
                description: 'Debug mode'
                type: boolean
                default: false
    push:
env:
    MY_WORKFLOW_VAR: "This is a secret"
    MY_OVERWRITTEN_VAR: "This is a secret"
jobs:
    echo-data:
        runs-on: ubuntu-latest
        # env:
        #     MY_WORKFLOW_VAR: "job"
        #     MY_OVERWRITTEN_VAR: "job"
        steps:
            - name: Display-information
              run: |
                    echo "Event name: $GITHUB_EVENT_NAME"
                    echo "GITHUB_SHA: $GITHUB_SHA"
                    echo "GITHUB_REF: $GITHUB_REF"
                    echo "GITHUB_ACTOR: $GITHUB_ACTOR"
                    echo "GITHUB_JOB: $GITHUB_JOB"
                    echo "GITHUB_WORKFLOW: $GITHUB_WORKFLOW"
                    echo "GITHUB_RUN_ID: $GITHUB_RUN_ID"
                    echo "GITHUB_RUN_NUMBER: $GITHUB_RUN_NUMBER"
            - name: Retrieve Variable
              run: echo "The value of the variable is ${{ vars.MY_VAR }}"
            - name: print Environment Variable
              env:
                MY_OVERWRITTEN_VAR: "step"
              run: |
                echo "Workflow env: ${{ env.MY_WORKFLOW_VAR }}"
                echo "Overwritten env: ${{ env.MY_OVERWRITTEN_VAR }}"
            - name: print Environment Variable
              run: |
                  echo "Workflow env: ${{ env.MY_WORKFLOW_VAR }}"
                  echo "Overwritten env: ${{ env.MY_OVERWRITTEN_VAR }}"