name: 09 - Using Functions

on: [ workflow_dispatch, pull_request ]

jobs:
  echo1:
    runs-on: ubuntu-latest

    steps:
    - name: Print PR title
      run: echo "PR title is ${{ github.event.pull_request.title }}"

    - name: Print PR labels
      run: echo "PR labels are ${{ join(github.event.pull_request.labels.*.name, ', ') }}"

    - name: Bug step
      if: github.event.action != 'cancelled' && contains(github.event.pull_request.title, 'fix')
      run: echo "This step will only run if the previous step failed"

    - name: Sleep for 20 seconds
      run: sleep 20

    - name: Failing step
      run: exit 1

    - name: I will asked be skipped
      if: success()
      run: echo "I will print if previous steps succeed."

    - name: I will executed
      if: failure()
      run: echo "I will print if previous steps fail."

    - name: I will executed
      if: github.event.pull_request == null && !cancelled()
      run: echo "I will always print, except when the workflow is cancelled"

    - name: I will executed when cancelled
      if: cancelled()
      run: echo "It has been cancelled"
