name: 11 - Working with Inputs

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'Skip deployment and only print build output'
        default: false
        type: boolean
      target:
        type: environment
        required: true
        description: "Which environment the workflow will target"
      tag:
        type: choice
        options:
        - v1
        - v2
        - v3
        default: v1
        description: "Release from which to build and deploy"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build
      run: echo "Building from tag ${{ github.event.inputs.tag }}"
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: ${{ github.event.inputs.target }}
    steps:
    - name: Deploy
      if: ${{ github.event.inputs.dry-run == 'false' }}
      run: echo "Deploying to ${{ github.event.inputs.target }}"
    - name: test
      run: echo "test iecho of the condition"
