name: 13 - Using Caching
on:
  workflow_dispatch:
    inputs:
      usec-cache:
        description: 'Whether to execute cache step'
        type: boolean
        default: true
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./13-caching/react-app
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '20'
    - name: Testing
      run: |
        npm run test
    - name: Building
      run: |
        npm run build
    - name: Deploying to nonprod
      run: |
        echo "Deploying to nonprod"
