name: 14 - Working with Artifacts
on:
  workflow_dispatch
jobs:
  test-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./14-artifacts/
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'
    - name: Dowload Cache dependencies
      uses: actions/cache@v3
      id: cache
      with:
        path: 14-artifacts/node_modules
        key: deps-node-modules-${{ hashFiles('14-artifacts/package-lock.json') }}
    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm --force ci
    - name: Unit test
      run: npm run test
    - name: Building
      run: |
        npm run build
    - name: Upload build files
      uses: actions/upload-artifact@v4
      with:
          name: app
          path: 14-artifacts/build
  deploy:
    runs-on: ubuntu-latest
    needs: test-build
    steps:
      - name: Download build artifact
        uses: actions/dowload-artifact@v4
        with:
          name: app
          path: build
      - name: Show folder structure
        run: ls -R