name: 15 - Working with Matrices
on:
  workflow_dispatch:

jobs:
  backwards-compatibility:
    name: ${{ matrix.os }}-${{ matrix.node }}
    strategy:
      fail-fast: false
      matrix:
        node: [18, 20, 21]
        os:
          - ubuntu-latest
          - windows-latest
        include:
          - os: ubuntu-latest
            node: 16
          - os: ubuntu-latest
            node: 21
            tag: experimental

    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Fail if experimental
        if: matrix.tag == 'experimental'
        run: exit 1
      - name: Perfom some test
        run: echo "Running tests on OS ${{ matrix.os }} and NodeJS ${{ matrix.node }}"

