name: 16 - Working with Environments
run-name: 16 - Working with Environments | env -${{ inputs.target-env }}

on:
  workflow_dispatch:
      inputs:
        target-env:
          type: environment
          description: "test"
          default: stagging
jobs:
  echo:
    runs-on: ubuntu-latest
    environment: ${{ inputs.target-env }}
    env:
      my-env-value: ${{ vars.MY_ENV_VALUE || 'deafult value' }}
    steps: 
      - name: Echo vars
        run: "Env variable: ${{ env.my-env-value }}"
