name: 17 - 1 - Custom Actions - Composite
run-name: 17 - 1 - Custom Actions - Composite | env - ${{ inputs.target-env }}
env:
  working-directory: 17-custom-actions

on: 
  workflow_dispatch:
    inputs:
        target-env:
            type: choice
            options:
                - dev
                  prod
jobs:
  build:
    runs-on: ubuntu-lastest
    defaults:
      run:
        working-directory: ./${{ env.working-directory }}
    steps:
      - name: Checkouts Code
        uses: actions/checkout@v4
      - name: Setup Node and NPM Dependencies
        uses: ./.github/actions/composite-cache-deps
      - name: Test
        run: npm run test
      - name: build
        run: npm run build
      


    